name: State removal
description: Remove a resource from terraform state file
title: "[State removal]"
labels: ["tfstate", "maintenance"]
body:
- type: input
  id: resource
  attributes:
    label: Terraform resource
    description: Terraform resource name that should be removed from state file
    placeholder: ex. resource.helm_release.metrics-server
  validations:
    required: true
- type: input
  id: env
  attributes:
    label: Environment
    description: Environment that it should be applied to.
    placeholder: ex. dev|hom|prod
  validations:
    required: true
