name: state-removal
on: 
  issues:
    types:
      - "opened"
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo "${{ steps.parse.outputs.data }}"