name: state-removal
on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Terraform resource name that should be removed from state file'
        required: true
        type: string
      env:
        description: 'Environment that it should be applied to'
        required: true
        type: choice
        options:
        - dev
        - hom
        - prod
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        run: echo "${{ inputs.resource }}" in "${{ inputs.env }}"